DROP TABLE IF EXISTS order_status;
CREATE TABLE order_status (
  id SERIAL PRIMARY KEY NOT NULL,
  order_id INTEGER REFERENCES orders(id) ON DELETE CASCADE NOT NULL,
  pending BOOLEAN DEFAULT TRUE,
  in_progress BOOLEAN DEFAULT FALSE,
  completed BOOLEAN DEFAULT FALSE
);
